#!/bin/sh

APACHEUSER=`ps aux | grep -E '[a]pache|[h]ttpd' | grep -v root | head -1 | cut -d\  -f1`
sudo setfacl -R -m u:$APACHEUSER:rwX -m u:`whoami`:rwX var
sudo setfacl -dR -m u:$APACHEUSER:rwX -m u:`whoami`:rwX var
