doctrine:
#    dbal:
#        types:
#            money:
#                class: Alsar\Ddd\Application\DomainBundle\Doctrine\MoneyType
    orm:
        entity_managers:
            default:
                mappings:
#                    AlsarDddWebBundle: ~
#                    AlsarDddDomainBundle:
#                        type:                 yml
#                        prefix:               Alsar\Ddd\Domain
