doctrine:
    dbal:
        types:
            money:
                class: Alsar\Ddd\DomainBundle\Doctrine\MoneyType
    orm:
        entity_managers:
            default:
                mappings:
                    AlsarDddDomainBundle:
                        type:                 yml
                        prefix:               Alsar\Ddd\Domain
                    ValueObject:
                        type:                 yml
                        dir:                  "%kernel.root_dir%/../src/DomainBundle/Resources/config/doctrine-external"
                        prefix:               Alsar\ValueObject
                        is_bundle:            false